### ISSUE TITLE
[Feature Request] Support of ChatGPT Enterprise

### ISSUE THREAD

**Issue by nc-ssommer** [TestCraft-App/test-craft-app-v1#2]
Hey, first of all thank you very much for that amazing plugin.

Our company policy would require to use [ChatGPT Enterprise](https://openai.com/chatgpt/enterprise). Therefore, it would be nice to have a setting to configure an own API-key.

Thanks

**Comment by damianpereira86** [comment]
Hi, thanks for your feedback!

We have this in our backlog already. I hope to get back to you soon.

**Comment by nc-ssommer** [comment]
I think this can be closed as an own API key can now be configured.
